### ISSUE TITLE
Where are the "HQ" and "VDSR"?

### ISSUE THREAD

**Issue by hooke007** [Alexkral/AviSynthAiUpscale#2]
Sorry, I do not see the HQ and VDSR `glsl` files in the release list. Is it too slow to use in the mpv? I want to test that in the mpv if possible.

**Comment by Alexkral** [comment]
The HQ and VDSR models were partially or fully trained with Matlab, so I didn't have the code to convert the weights to GLSL and I only made the code to convert them to HLSL. In the next release there will be mpv hooks for all models, but for 4k upscaling with the HQ models you will probably need one of the latest GPUs from Nvidia or AMD.

**Comment by hooke007** [comment]
Wow, excellent!
