### ISSUE TITLE
Script error: There is not function named 'ConvertToShader'.

### ISSUE THREAD

**Issue by newcapricasean** [Alexkral/AviSynthAiUpscale#7]
I have copied the avisynth script, and the shaders folder, into my 64 bit plugins directory, but this is the result I get, when trying to invoke the script...

Script error: There is not function named 'ConvertToShader'.

**Comment by Alexkral** [comment]
Sorry for the delay, you also need AviSynth Shader. If it still doesn't work, take a look of this post:

[https://forum.doom9.org/showthread.php?p=1922079#post1922079](https://forum.doom9.org/showthread.php?p=1922079#post1922079)
