### ISSUE TITLE
Can this tool be modified to handle unsymmetrical upscale.  like 960x720->1920x1080

### ISSUE THREAD

**Issue by chowderhead** [Alexkral/AviSynthAiUpscale#9]
I have a 289GB folder of 960x720 that I want to upscale to 1920x1080.  

I am very interested in your program but I need asymmetric upsize to work (as I think most would.)
960x720 is quite common on older 4:3 animes and there's a group that wants to upscale and a group that says leave it alone.

I say upsize them all and most think that way.  I'm trying to do my part by upscaling this MASSIVE hand drawn epic called Legend of the Galactic Heroes to 1080 with tons of picture correction I call the "NVIDIA Effect" by balancing color and upping the frame speed lowering brightness and white wash these old animes are famous for.  NVIDIA also has a sharpening function and noise reduction all based on CUDA.  Im INCREDIBLY excited about AI helping us upgrade these old films to modern style with what could become almost DIGITAL PERFECTION with enough AI "thought" put into keeping these upscales pure and beautiful with AI's help.

Let me know if you can make the changes necessary for my upscale to work.  I would LOVE to try an AI guided hand in this upscale.   Im not minimizing the amount of work it would take because I simply have no idea.  If its too much work just say so, otherwise Id be happy to share my outcomes with you if you are interested in doing this with me.  I see the program and understand it a little bit but the actual logic behind it is beyond me. (at least for the moment).  But I intend to stare at it long enough the logic will hit me eventually.

Any instruction or help understanding the AI logic would be appreciated if you feel like sharing.
Its an amazingly short program.

Anyway.  let me know UP or DOWN on the idea so if your not interested Ill move on and just use Spline36  to upscale this whopper.

When I upscale I also edit out the excess intro and exit music of the nearly 200 video files which makes for less data to seed in torrents and easy viewing without all the fast forwarding through the SAME BORING INTROS AND EXITS. and sometimes even soda and other drink ads.  GOOD GOD.   I edited almost 2000 minutes of this crap in one series I upscaled.

Any, I hope u get this and we can try this experiment to beat all the other upscale algorithms.

cheers mate
Randy Kuehn
crunchy@kuehnfamily.com

**Comment by Alexkral** [comment]
Hi, sorry for answering so late, I don't usually check if there is any issue.

I'm not really into this anymore, but if you're feeling adventurous you could train your own models. For the easiest solution you would need Matlab, but then it's not that difficult, you could train a full VDSR model with different ratio between width and height, and use it in Matlab itself without any further implementation needed. Here you have a very good explanation of the process:

[https://www.mathworks.com/help/images/single-image-super-resolution-using-deep-learning.html](https://www.mathworks.com/help/images/single-image-super-resolution-using-deep-learning.html)

Apart from the fact that my models are more reduced and have a different architecture, the main difference is that I use Lanczos for upscaling, which makes the result sharper. A different sharp upscaler like Sinc would also be suitable. Also, if this is for anime, you should use an anime dataset, you could also do it yourself.

The result would be very good for sure, but I am not sure that the perceptual difference would be too significant.
